name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup PNPM
      uses: pnpm/action-setup@v2.2.1

    - name: Install and Build
      run: |
        pnpm i
        pnpm run build

    - name: Setup Aliyun OSS
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}

    - name: Delete old files on OSS
      run: ossutil rm -rf oss://fx-website-list/

    - name: Copy to OSS
      run: ossutil cp -rf docs/.vuepress/dist oss://fx-website-list/
